#image:
#  repository: "ghcr.io/myuser/kubewarden-controller"
#  tag: "latest"
telemetry:
  enabled: false
policyServer:
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: debug
auditScanner:
  enable: true
